# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b787366b2d818154a7af5f094d63d0462b4a615f8fe289e856475a67d58162fa5f6f3da212576044ecd47df072feee8a9aff542518b427f77bdc615ad990d803

test:
  secret_key_base: ad05c71a16d97099a4a91c1da2f9d64f45495963ff3744cf7403d73db3aaf5022745872b351c39cd7fd0f61e5839bcd99b62c0eeea7bc902f8366dc27d295c3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
